### ISSUE TITLE
Updated vignette.

### ISSUE THREAD

**Issue by hntek** [peter0083/LufthansaR#22]
---
title: "LufthansaR"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    keep_md: true
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE}
#library(glue)
```

## Introduction to LufthansaR

`LufthansaR` is an API wrapper package for R. It enables programmers to access to [Lufthansa Open API](https://developer.lufthansa.com/docs) from R environment. 

This document introduces you to LufthansaR's basic set of tools, and show how to use them. Once you have installed the package, read `vignette("LufthansaR")` to learn more.

## Lufthansa Open API

To have access to Lufthansa Open API, one has to sign in to Mashery, Lufthansa's developer platform, and apply for a key. Please visit [here](https://developer.lufthansa.com/docs/API_basics/). Once you are registered, you will be given:

- a key and
- a secret

These two values can be exchanged for a _short-lived_ access token. A valid access token must be sent with every API request while accessing any Lufthansa's API. In other words, every Lufthansa API requires you to pass Oauth token when getting the data from it. 

## How to install LufthansaR

You can install `LufthansaR` development version from GitHub

```{r, eval=FALSE}
devtools::install_github("peter0083/LufthansaR")
```

CRAN version of the package will be scheduled to be added in the next version.

## How to deal with Lufthansa Open API credentials

TBD

## Usage

You can load `LufthansaR` as follows.

```{r, eval=FALSE}
library(LufthansaR)
```

This will load the core `lufthansaR` functions. 

## How to see the active token used

Get the current token being used by the package

```{r, eval=FALSE}
LufthansaR::get_token()
```

Each token is valid for a specified period of time. When the token is valid, `LufthansaR` uses the `Client ID` and `Client Secret` in your `.Renviron`.

## How to get flight status

This will print out the flight's information 
```{r}
f_status <- LufthansaR::get_flight_status("LH493")
```

Default is today's data. However, you can call 5 days in the future by passing `dep_date="2018-04-15"` argument. The departure date (YYYY-MM-DD) in the local time of the departure airport.

Since the function returns httr content object, you can access to different attributes of the content:

```{r}
# Departure Airport abbreviation
f_status$Departure$AirportCode

# Scheduled Departure Time (departure local time)
f_status$Departure$ScheduledTimeLocal$DateTime

# Departure Terminal
f_status$Departure$Terminal$Name

# Departure Status
f_status$Departure$TimeStatus$Definition

# Arrival Airport abbreviation
f_status$Arrival$AirportCode

# Scheduled Arrival Time (arrival local time)
f_status$Arrival$ScheduledTimeLocal$DateTime

# Arrival Terminal
f_status$Arrival$Terminal$Name

# Arrival Status
f_status$Arrival$TimeStatus$Definition
```

## Getting status of flights arriving at a particular airport

```{r, echo=FALSE}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggmap))
suppressPackageStartupMessages(library(lubridate))

```

To obtain the information about flights at the arrival airport,

```{r, eval=FALSE}
get_flight_status_arrival(airport = "YVR", fromDateTime = "2018-04-13T00:00")
```
The output is the `httr` parsed content. The format of `fromDateTime` is `YYYY-MM-DDTHH:MM`. This is ISO-8601 date format.

Let's assume that we are interested in flights arriving at `FRA` around this time. And let's assume we are interested in showing some departure delays of those flights in a visualization.

```{r}

# This to get the current local time at FRA and convert it to the ISO-8601 format.
tm <- as.POSIXlt(Sys.time(), tz="Europe/Berlin", "%Y-%m-%dT%H:%M")
tm_FRA <- strftime(tm,  "%Y-%m-%dT%H:%M")

# to parse the content
parsed_content <- get_flight_status_arrival(airport = "FRA", fromDateTime = tm_FRA)
```

You can see the content return by typing `parsed_content`. It is possible that there might not be any flight arriving at the time specified. Let's first see how many flights the API returns.

```{r}
if (parsed_content$FlightStatusResource$Meta$TotalCount == 1){
  (no_flight_returned <-parsed_content$FlightStatusResource$Meta$TotalCount)
} else{
  (no_flight_returned <- summary(parsed_content$FlightStatusResource$Flights)[1])
}
```

In the following, a visualization is created by using the return content for departure delay for those flight arriving at FRA.

```{r, fig.width=7.5, fig.height=5, fig.align="center"}
# The following is performed if the API returns some flight information

if(!(is.nan(no_flight_returned) | no_flight_returned <= 1)){

  flight_departure_data <- data.frame(dept_airport = rep(NA, no_flight_returned), 
            scheduled_dept =rep(NA, no_flight_returned), actual_dept =rep(NA, no_flight_returned))
  
  for (i in 1:no_flight_returned){
  
    flight_departure_data$dept_airport[i] <- 
      parsed_content$FlightStatusResource$Flights[[1]][[i]]$Departure$AirportCode
  
    flight_departure_data$scheduled_dept[i] <-  
      parsed_content$FlightStatusResource$Flights[[1]][[i]]$Departure$ScheduledTimeLocal$DateTime
  
    flight_departure_data$actual_dept[i] <- 
      ifelse (is.null(parsed_content$FlightStatusResource$Flights[[1]][[i]]$Departure$ActualTimeLocal$DateTime), NA, parsed_content$FlightStatusResource$Flights[[1]][[i]]$Departure$ActualTimeLocal$DateTime)
  }

  flight_departure_data$delay <-
    -as.numeric(as.duration(interval(ymd_hm(flight_departure_data$actual_dept),                                                                    ymd_hm(flight_departure_data$scheduled_dept))), "minutes")

  flight_departure_data<- flight_departure_data %>% 
    mutate(status = ifelse(is.na(delay), "not departed", 
                         ifelse(delay>0, "delayed departure", "early/on-time"))) %>% 
    mutate(delay = ifelse(is.na(delay), 1,  delay)) 

  ggplot(data=flight_departure_data, aes(x=as.factor(dept_airport), y=delay)) +
    geom_bar(stat="identity", aes(fill=status)) + 
    coord_flip() +
    ggtitle(paste0("Delay Status at the Departure Airports for the Flights arriving at ", "FRA")) +
    theme(legend.position = "bottom") +
    xlab("Airport") +
    ylab("Delay (minutes)")

} else {
  print("No more than one flight information available at this time!")
}

```

## Getting status of flights departing from a particular airport 

To obtain the information about flights at the departure airport,

```{r, eval=FALSE}
get_flight_status_departure(airport = "YVR", fromDateTime = "2018-04-13T00:00")
```
The output is the `httr` parsed content. The format of `fromDateTime` is `YYYY-MM-DDTHH:MM`. This is ISO-8601 date format.

Let's assume that we are interested in flights departing from `FRA` around this time. 

```{r}

# This to get the current local time at FRA and convert it to the ISO-8601 format.
tm <- as.POSIXlt(Sys.time(), tz="Europe/Berlin", "%Y-%m-%dT%H:%M")
tm_FRA <- strftime(tm,  "%Y-%m-%dT%H:%M")

# to parse the content
parsed_content <- get_flight_status_departure(airport = "FRA", fromDateTime = tm_FRA)
```

You can see the content return by typing `parsed_content`. It is possible that there might not be any flight arriving at the time specified. It is possible that there might not be any flight arriving at the time specified. Let's first see how many flights the API returns.

```{r}
# to count the number of flights returned
if (parsed_content$FlightStatusResource$Meta$TotalCount == 1){
  (no_flight_returned <-parsed_content$FlightStatusResource$Meta$TotalCount)
} else{
  (no_flight_returned <- summary(parsed_content$FlightStatusResource$Flights)[1])
}
```
```{r}
# The following is performed if the API returns more than one flight

if(!(is.nan(no_flight_returned) | no_flight_returned <= 1)){

  flight_departure_data <- data.frame(flight_code = rep(NA, no_flight_returned), 
            scheduled_dept =rep(NA, no_flight_returned), destination_airport =rep(NA, no_flight_returned), arrival_time =rep(NA, no_flight_returned))
  
  for (i in 1:no_flight_returned){
  
    flight_departure_data$flight_code[i] <- 
      paste0( parsed_content$FlightStatusResource$Flights[[1]][[i]]$MarketingCarrier$AirlineID,parsed_content$FlightStatusResource$Flights[[1]][[i]]$MarketingCarrier$FlightNumber)
  
    flight_departure_data$scheduled_dept[i] <-  
      parsed_content$FlightStatusResource$Flights[[1]][[i]]$Departure$ScheduledTimeLocal$DateTime
  
    flight_departure_data$destination_airport[i] <- parsed_content$FlightStatusResource$Flights[[1]][[i]]$Arrival$AirportCode
    
    flight_departure_data$arrival_time[i] <- parsed_content$FlightStatusResource$Flights[[1]][[i]]$Arrival$ScheduledTimeLocal
  }

flight_departure_data
  
} else {
  print("No flight information available at this time!")
}

```

**Comment by amygoldlist** [comment]
Should we close this issue?
