### ISSUE TITLE
get_flight_status

### ISSUE THREAD

**Issue by hntek** [peter0083/LufthansaR#8]
Just realized that function uses `glue` library. If someone does not have that library (l didn't have), function will not work. I was just looking at Jenny's note at `http://stat545.com/packages06_foofactors-package.html#define_the_first_function`. She says "Package code should never contain a call to library()". Do you know how to handle libraries in the package? @peter0083 @joesdesk @amygoldlist

**Comment by hntek** [comment]
I added `glue` in the DESCRIPTION file in `arrival_departure` branch. Once it is merged to the original, this issue will be taken care.

**Comment by hntek** [comment]
Just realized when I pull the updated origin, I can see the added package `glue` in DESCRIPTION when I open the file in my local. However, when I click on the DESCRIPTION file on the github I can not see the `glue` in the description. Any idea why? @peter0083 @joesdesk @amygoldlist

**Comment by joesdesk** [comment]
Did you pull from the arrival_departure branch or master branch?
